name: kakkonan

env:
  DENO_VERSION: 1.x

on: push

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version ${{ env.DENO_VERSION }}
      - name: Format
        run: |
          deno fmt --check

